services:
  nginx:
    image: nginx:1.29.4-alpine
    container_name: nginx-lab
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lab-network
    depends_on:
      - app-node

  app-node:
    build: ./app-node
    volumes:
      - ./app-node:/app 
      - /app/node_modules
    deploy:
      replicas: 3
    networks:
      - lab-network
  
  app-python:
    build: ./app-python
    volumes:
      - ./app-python:/app
    networks:
      - lab-network
    # ports:
    #   - "8000:8000"


networks:
  lab-network:
    external: true