services:
  nginx:
    image: nginx:1.29.4-alpine
    container_name: nginx-lab
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lab-network
    depends_on:
      - app-node

  app-node:
    build: ./app-node
    volumes:
      - ./app-node:/app 
      - /app/node_modules
    deploy:
      replicas: 3
    networks:
      - lab-network
    env_file:
      - ./app-node/.env
    command: sh -c "npm install && npm run dev"

  db-mysql:
    image: mysql:8.0
    labels:
      - "description=MySQL database for the node app"
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - lab-network
  
  db-postgres:
    image: postgres:14
    labels:
      - "description=Postgres database for the python app"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: python_app
    networks:
      - lab-network

  app-python:
    build: ./app-python
    volumes:
      - ./app-python:/app
    networks:
      - lab-network
    # ports:
    #   - "8000:8000"

volumes:
  mysql_data:
  postgres_data:

networks:
  lab-network: